include ../def.makefile

MODULE = pfft

OBJS = element.o g2gPoint.o grid.o gridElement.o gridIndex.o interpMat.o kernelIntegration.o projectMat.o stencil.o utils.o

include $(UTIL_DIR)/share.cc.makefile

