include ../def.makefile

MODULE = fastMax

OBJS = node.o calcaoneoverr.o calcpOneOverR.o charge.o conductor.o const_def.o ext_node_pair.o extractz.o fastsub.o frequencysample.o\
 generate_dipoles.o inductance.o initialize_discretization.o internal_node.o layer.o layerenv.o resistance.o\
 structure.o sysformation.o

include $(UTIL_DIR)/share.cpp.makefile


